"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type Dividend = { symbol: string; companyName: string; dividendPerShare: number; currency: "IDR"; dividendKind: string; cumDateRegular: string; exDateRegular: string | null; recordDate: string | null; paymentDate: string | null; announcementDate: string | null; sourceUrl: string; sourceReference: string | null };
type Payload = { events: Dividend[]; total: number; syncedAt: string | null; coverageStart: string | null; warnings: string[]; error?: string };
const money = new Intl.NumberFormat("id-ID", { maximumFractionDigits: 2 });
const date = (value: string | null) => value ? new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeZone: "Asia/Jakarta" }).format(new Date(`${value}T00:00:00+07:00`)) : "—";

export default function DividendPage() {
  const [view, setView] = useState<"eligible" | "pending">("eligible"); const [search, setSearch] = useState(""); const [submittedSearch, setSubmittedSearch] = useState("");
  const [page, setPage] = useState(1); const [data, setData] = useState<Payload>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  const load = useCallback(async (targetPage: number, targetView: "eligible" | "pending", targetSearch: string) => {
    setLoading(true); setError(undefined);
    try { const params = new URLSearchParams({ page: String(targetPage), view: targetView }); if (targetSearch) params.set("search", targetSearch); const response = await fetch(`/api/dividends?${params}`, { cache: "no-store" }); const payload = await response.json() as Payload; if (!response.ok) throw new Error(payload.error ?? "Kalender dividen belum tersedia."); setData(payload); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Kalender dividen belum tersedia."); } finally { setLoading(false); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(page, view, submittedSearch); }, 0); return () => window.clearTimeout(timer); }, [load, page, view, submittedSearch]);
  const pages = Math.max(1, Math.ceil((data?.total ?? 0) / 10));
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jakarta", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const label = view === "eligible" ? "Masih bisa dibeli untuk dividen" : "Cum date lewat, pembayaran menunggu";
  const todayEvents = useMemo(() => data?.events.filter((event) => event.cumDateRegular === today).length ?? 0, [data, today]);
  return <main className="min-h-screen bg-[#f6f8fb] px-5 py-10 text-slate-900"><div className="mx-auto max-w-6xl">
    <Link href="/" className="text-sm font-semibold text-indigo-600 hover:text-indigo-800">← Kembali ke screener</Link>
    <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-sm font-bold text-indigo-600">Kalender dividen IDX</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Tahu batas terakhir beli saham untuk dividen.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Tanggal yang ditampilkan adalah cum dividen di Pasar Reguler & Negosiasi dari pengumuman KSEI. Beli dan tahan sampai penutupan pada tanggal tersebut agar memenuhi jadwal yang diumumkan; periksa kembali status order dan pengumuman resmi sebelum transaksi.</p>
      <div className="mt-6 flex flex-wrap gap-3"><button onClick={() => { setView("eligible"); setPage(1); }} className={`rounded-xl px-4 py-2 text-sm font-bold ${view === "eligible" ? "bg-indigo-600 text-white" : "border border-slate-300 bg-white"}`}>Masih bisa dibeli</button><button onClick={() => { setView("pending"); setPage(1); }} className={`rounded-xl px-4 py-2 text-sm font-bold ${view === "pending" ? "bg-indigo-600 text-white" : "border border-slate-300 bg-white"}`}>Pembayaran menunggu</button></div>
      <form onSubmit={(event) => { event.preventDefault(); setPage(1); setSubmittedSearch(search.trim()); }} className="mt-5 flex gap-3"><input aria-label="Cari saham dividen" value={search} onChange={(event) => setSearch(event.target.value.toUpperCase())} placeholder="Cari kode atau nama saham" className="min-w-0 flex-1 rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-indigo-500" /><button className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold">Cari</button></form>
    </section>
    {todayEvents > 0 && <p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Ada {todayEvents} cum date hari ini. Batas pembelian mengikuti penutupan Pasar Reguler; cek jam perdagangan dan status order di broker.</p>}
    {error && <p role="alert" className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}
    {data?.warnings.length ? <details className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><summary className="cursor-pointer font-semibold">{data.warnings.length} catatan sinkronisasi KSEI</summary><ul className="mt-3 space-y-2">{data.warnings.map((warning) => <li key={warning}>• {warning}</li>)}</ul></details> : null}
    <section aria-busy={loading} className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold">{label}</h2><p className="mt-1 text-xs text-slate-500">{data ? `${data.total} pengumuman · sinkronisasi ${data.syncedAt ? new Date(data.syncedAt).toLocaleString("id-ID", { timeZone: "Asia/Jakarta" }) + " WIB" : "belum ada"}` : "Memuat cache resmi"}</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{data?.events.length ?? 0} di halaman</span></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Saham</th><th className="px-4 py-3">Dividen / saham</th><th className="px-4 py-3">Terakhir beli</th><th className="px-4 py-3">Ex date</th><th className="px-4 py-3">Pembayaran</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{data?.events.map((event) => <tr key={event.sourceUrl}><td className="px-4 py-4"><p className="font-bold">{event.symbol}</p><p className="mt-1 max-w-72 truncate text-xs text-slate-500">{event.companyName}</p><p className="mt-1 text-xs text-slate-400">{event.dividendKind}</p></td><td className="px-4 py-4 font-semibold">Rp{money.format(event.dividendPerShare)}</td><td className="px-4 py-4"><p className="font-semibold text-indigo-700">{date(event.cumDateRegular)}</p><p className="mt-1 text-xs text-slate-500">Pasar Reguler & Negosiasi</p></td><td className="px-4 py-4">{date(event.exDateRegular)}</td><td className="px-4 py-4">{date(event.paymentDate)}</td><td className="px-4 py-4"><a href={event.sourceUrl} target="_blank" rel="noreferrer" className="text-xs font-bold text-indigo-600 hover:text-indigo-800">Pengumuman KSEI ↗</a></td></tr>)}</tbody></table></div>
      {!loading && !data?.events.length && <p className="p-10 text-center text-sm text-slate-500">Tidak ada pengumuman yang sesuai tampilan ini.</p>}{loading && <p className="p-8 text-center text-sm text-slate-500">Memuat kalender dividen…</p>}
    </section>
    <nav aria-label="Halaman kalender dividen" className="mt-4 flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4"><button disabled={loading || page <= 1} onClick={() => setPage(page - 1)} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold disabled:opacity-40">Sebelumnya</button><span className="text-sm">Halaman {page} dari {pages}</span><button disabled={loading || page >= pages} onClick={() => setPage(page + 1)} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold disabled:opacity-40">Berikutnya</button></nav>
    <p className="mt-6 pb-10 text-xs leading-5 text-slate-500">Sumber jadwal: KSEI. Nilai dividen adalah bruto per saham sesuai pengumuman dan belum menghitung pajak atau biaya. Kalender ini bukan rekomendasi membeli saham.</p>
  </div></main>;
}
